name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    #This  workflow contains a single job called "build"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   
    - name: Run make command
      run: make hello  
